# HD1 Channel Configuration
# Default channel settings and server behavior

defaults:
  # Default channel for new users
  default_channel: "channel_one"
  
  # Channel to use if default is unavailable
  fallback_channel: "channel_two"
  
  # Auto-join behavior
  auto_join_on_session_create: true
  
  # Channel discovery settings
  discovery:
    scan_directory: "/opt/hd1/share/channels"
    cache_duration_seconds: 300
    include_disabled: false

# Channel-specific overrides
channels:
  channel_one:
    enabled: true
    priority: 1
    description: "Primary collaborative environment for general holodeck activities"
    max_clients: 100
    auto_apply_environment: true
    
  channel_two:
    enabled: true
    priority: 2
    description: "Advanced physics simulation and experimentation environment"
    max_clients: 50
    auto_apply_environment: true
    
  channel_three:
    enabled: true
    priority: 3
    description: "Underwater exploration and marine research simulation environment"
    max_clients: 75
    auto_apply_environment: true

# Server behavior settings
server:
  # Channel cleanup settings
  cleanup_empty_channels_after_minutes: 30
  
  # Channel switching limits
  max_channel_switches_per_minute: 10
  
  # Environment synchronization
  sync_environment_on_join: true
  
  # Logging
  log_channel_events: true