# HD1 World Configuration
# Default world settings and server behavior

defaults:
  # Default world for new users
  default_world: "world_one"
  
  # World to use if default is unavailable
  fallback_world: "world_two"
  
  # Auto-join behavior
  auto_join_on_session_create: true
  
  # World discovery settings
  discovery:
    scan_directory: "/opt/hd1/share/worlds"
    cache_duration_seconds: 300
    include_disabled: false

# World-specific overrides
worlds:
  world_one:
    enabled: true
    priority: 1
    description: "Primary collaborative environment for general holodeck activities"
    max_clients: 100
    auto_apply_environment: true
    
  world_two:
    enabled: true
    priority: 2
    description: "Advanced physics simulation and experimentation environment"
    max_clients: 50
    auto_apply_environment: true
    
  world_three:
    enabled: true
    priority: 3
    description: "Underwater exploration and marine research simulation environment"
    max_clients: 75
    auto_apply_environment: true

# Server behavior settings
server:
  # World cleanup settings
  cleanup_empty_worlds_after_minutes: 30
  
  # World switching limits
  max_world_switches_per_minute: 10
  
  # Environment synchronization
  sync_environment_on_join: true
  
  # Logging
  log_world_events: true